//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodDatabase.Core.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FoodDatabase.Core.Resources.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hinzufügen.
        /// </summary>
        internal static string AddButton {
            get {
                return ResourceManager.GetString("AddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hinzugefügt am {0}.
        /// </summary>
        internal static string AddedOn {
            get {
                return ResourceManager.GetString("AddedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alkohol.
        /// </summary>
        internal static string Alcohol {
            get {
                return ResourceManager.GetString("Alcohol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kalzium.
        /// </summary>
        internal static string Calcium {
            get {
                return ResourceManager.GetString("Calcium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kohlenhydrate.
        /// </summary>
        internal static string Carbs {
            get {
                return ResourceManager.GetString("Carbs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chlor.
        /// </summary>
        internal static string Chlorine {
            get {
                return ResourceManager.GetString("Chlorine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cholesterin.
        /// </summary>
        internal static string Cholesterol {
            get {
                return ResourceManager.GetString("Cholesterol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support kontaktieren.
        /// </summary>
        internal static string ContactSupport {
            get {
                return ResourceManager.GetString("ContactSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kupfer.
        /// </summary>
        internal static string Copper {
            get {
                return ResourceManager.GetString("Copper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kcal/Tag.
        /// </summary>
        internal static string DailyKcal {
            get {
                return ResourceManager.GetString("DailyKcal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{1} ({2} Uhr).
        /// </summary>
        internal static string DiaryItemProduct {
            get {
                return ResourceManager.GetString("DiaryItemProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tagebuch.
        /// </summary>
        internal static string DiaryTitle {
            get {
                return ResourceManager.GetString("DiaryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ballaststoffe.
        /// </summary>
        internal static string DiateryFiber {
            get {
                return ResourceManager.GetString("DiateryFiber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fett.
        /// </summary>
        internal static string Fat {
            get {
                return ResourceManager.GetString("Fat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fett (gesättigt).
        /// </summary>
        internal static string FatSaturated {
            get {
                return ResourceManager.GetString("FatSaturated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fluor.
        /// </summary>
        internal static string Fluorine {
            get {
                return ResourceManager.GetString("Fluorine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Von einer anderen App hinzugefügt.
        /// </summary>
        internal static string FromExternal {
            get {
                return ResourceManager.GetString("FromExternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In deinem Tagebuch.
        /// </summary>
        internal static string InDiary {
            get {
                return ResourceManager.GetString("InDiary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jod.
        /// </summary>
        internal static string Iodine {
            get {
                return ResourceManager.GetString("Iodine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eisen.
        /// </summary>
        internal static string Iron {
            get {
                return ResourceManager.GetString("Iron", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/{1} Kcal verbraucht.
        /// </summary>
        internal static string KcalUsed {
            get {
                return ResourceManager.GetString("KcalUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angemeldet als {0}.
        /// </summary>
        internal static string LoggedInAs {
            get {
                return ResourceManager.GetString("LoggedInAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anmelden.
        /// </summary>
        internal static string LoginButton {
            get {
                return ResourceManager.GetString("LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler bei der Anmeldung. Bitte noch mal versuchen..
        /// </summary>
        internal static string LoginError {
            get {
                return ResourceManager.GetString("LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Melde dich bei deinem Konto an.
        /// </summary>
        internal static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abmelden.
        /// </summary>
        internal static string LogoutButton {
            get {
                return ResourceManager.GetString("LogoutButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magensium.
        /// </summary>
        internal static string Magensium {
            get {
                return ResourceManager.GetString("Magensium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magnesium.
        /// </summary>
        internal static string Magnesium {
            get {
                return ResourceManager.GetString("Magnesium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mangan.
        /// </summary>
        internal static string Manganese {
            get {
                return ResourceManager.GetString("Manganese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mangan.
        /// </summary>
        internal static string Mangenese {
            get {
                return ResourceManager.GetString("Mangenese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du bist nicht angemeldet.
        /// </summary>
        internal static string NotLoggedIn {
            get {
                return ResourceManager.GetString("NotLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nährwerte für {0}{1}.
        /// </summary>
        internal static string NutrionalDataFor {
            get {
                return ResourceManager.GetString("NutrionalDataFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort.
        /// </summary>
        internal static string PasswordHint {
            get {
                return ResourceManager.GetString("PasswordHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phosphor.
        /// </summary>
        internal static string Phosphor {
            get {
                return ResourceManager.GetString("Phosphor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kalium.
        /// </summary>
        internal static string Potassium {
            get {
                return ResourceManager.GetString("Potassium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schnell eine Vorlage auswählen.
        /// </summary>
        internal static string PresetDescription {
            get {
                return ResourceManager.GetString("PresetDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eiweiß.
        /// </summary>
        internal static string Proteins {
            get {
                return ResourceManager.GetString("Proteins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registriere dich bei fddb.info.
        /// </summary>
        internal static string RegisterText {
            get {
                return ResourceManager.GetString("RegisterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salz.
        /// </summary>
        internal static string Salt {
            get {
                return ResourceManager.GetString("Salt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speichern.
        /// </summary>
        internal static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suche.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eigene Menge eingeben.
        /// </summary>
        internal static string SelectCustomDescription {
            get {
                return ResourceManager.GetString("SelectCustomDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Füge diese Mahlzeit dem Tagebuch hinzu.
        /// </summary>
        internal static string ServingDescription {
            get {
                return ResourceManager.GetString("ServingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einstellungen.
        /// </summary>
        internal static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zucker.
        /// </summary>
        internal static string Sugar {
            get {
                return ResourceManager.GetString("Sugar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schwefel.
        /// </summary>
        internal static string Sulfur {
            get {
                return ResourceManager.GetString("Sulfur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktualisiere.
        /// </summary>
        internal static string Updating {
            get {
                return ResourceManager.GetString("Updating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nutzername oder E-Mail.
        /// </summary>
        internal static string UsernameHint {
            get {
                return ResourceManager.GetString("UsernameHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vitamin A.
        /// </summary>
        internal static string VitA {
            get {
                return ResourceManager.GetString("VitA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vitamin B1.
        /// </summary>
        internal static string VitB1 {
            get {
                return ResourceManager.GetString("VitB1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vitamin B12.
        /// </summary>
        internal static string VitB12 {
            get {
                return ResourceManager.GetString("VitB12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vitamin B2.
        /// </summary>
        internal static string VitB2 {
            get {
                return ResourceManager.GetString("VitB2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vitamin B6.
        /// </summary>
        internal static string VitB6 {
            get {
                return ResourceManager.GetString("VitB6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vitamin C.
        /// </summary>
        internal static string VitC {
            get {
                return ResourceManager.GetString("VitC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vitamin D.
        /// </summary>
        internal static string VitD {
            get {
                return ResourceManager.GetString("VitD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vitamin E.
        /// </summary>
        internal static string VitE {
            get {
                return ResourceManager.GetString("VitE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wasser.
        /// </summary>
        internal static string Water {
            get {
                return ResourceManager.GetString("Water", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zink.
        /// </summary>
        internal static string Zinc {
            get {
                return ResourceManager.GetString("Zinc", resourceCulture);
            }
        }
    }
}
